version: "3.8"

services:
  crypto-pipeline:
    build: .
    container_name: crypto_pipeline
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
      - POLLING_INTERVAL=60
    restart: unless-stopped
